export const API_ENDPOINTS = {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    SIGNUP: '/auth/signup',
    GET_USER: '/user',
    INTAKE_RANGE: '/log/intake/range',
    ADD_CALORIE_INTAKE: '/log/intake',
    GET_CALORIE_INTAKE: '/log/intake',
    DELETE_CALORIE_INTAKE: '/log/intake',
    GET_FRIEND_DAILY_LOG: '/log/friend',
    SEARCH_FOOD: '/foods/info',
    ADD_FOOD: '/foods/info',
    GET_FRIENDS: '/user-profile/connections',
    GET_AVAILABLE_USERS: '/user-profile/feed',
    GET_PENDING_REQUESTS: '/user-profile/requests',
    SEND_CONNECTION_REQUEST: '/connection/send',
    REVIEW_CONNECTION_REQUEST: '/connection/review',
    ADD_WORKOUT: '/workout',
    GET_WORKOUTS: '/workout',
    DELETE_WORKOUT: '/workout',
    GET_FITNESS_METRICS: '/fitness-metrics',
    GET_LATEST_FITNESS_METRICS: '/fitness-metrics/latest',
    GET_RECENT_FITNESS_METRICS: '/fitness-metrics/recent',
    ADD_FITNESS_METRICS: '/fitness-metrics',
    UPDATE_FITNESS_METRICS: '/fitness-metrics',
    DELETE_FITNESS_METRICS: '/fitness-metrics'
}